Repository Viddesh1/RL, pull requests merged in 2023-04, with the labels that each got.

#5 Hyperparameter, environmemnt and Q-table created #4
  Frozen_lake.ipynb
Labels: enhancement

#10 Action function is created #6
  Frozen_lake.ipynb
Labels: enhancement

#11 #7 Q formula created
  Frozen_lake.ipynb
  Q-Formula.png
Labels: enhancement

#12 #8 Policy is created by Q-table
  Frozen_lake.ipynb
  frozenLake_qTable.pkl
Labels: enhancement

#13 #8 #9 Reading pickle file
  Frozen_lake.ipynb
Labels: enhancement

#23 Update README.md Added GIF
  README.md
Labels: documentation

#27 added requirements.txt
  Mini_Project.ipynb
  Requirements.txt
Labels: enhancement, good first issue

#31 #30 Done! Comment and formating changed
  Mini_Project.ipynb
Labels: documentation, enhancement

#33 #32 Consise comment added
  Mini_Project.ipynb
Labels: documentation
